version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: marten-postgres
    restart: always
    environment:
      POSTGRES_USER: marten_user
      POSTGRES_PASSWORD: marten_password
      POSTGRES_DB: marten_db
    ports:
      - "5432:5432"


  dotnet-api:
      image: mcr.microsoft.com/dotnet/aspnet:8.0
      container_name: marten-dotnet-api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080" # Expose the API on port 5000
      depends_on:
        - postgres
      environment:
        ConnectionStrings__MartenDatabase: Host=marten-postgres;Port=5432;Database=marten_db;Username=marten_user;Password=marten_password